/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as UniteRouteImport } from './routes/unite'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiContactoRouteImport } from './routes/api/contacto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const UniteRoute = UniteRouteImport.update({
  id: '/unite',
  path: '/unite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactoRoute = ApiContactoRouteImport.update({
  id: '/api/contacto',
  path: '/api/contacto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/unite' | '/api/apply' | '/api/contacto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/unite' | '/api/apply' | '/api/contacto'
  id: '__root__' | '/' | '/contacto' | '/unite' | '/api/apply' | '/api/contacto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  UniteRoute: typeof UniteRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiContactoRoute: typeof ApiContactoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unite': {
      id: '/unite'
      path: '/unite'
      fullPath: '/unite'
      preLoaderRoute: typeof UniteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacto': {
      id: '/api/contacto'
      path: '/api/contacto'
      fullPath: '/api/contacto'
      preLoaderRoute: typeof ApiContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  UniteRoute: UniteRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiContactoRoute: ApiContactoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
