/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UniteRouteImport } from './routes/unite'
import { Route as ApiApplyRouteImport } from './routes/api/apply'
import { Route as ApiContactoRouteImport } from './routes/api/contacto'
import { Route as ApiCotizacionRouteImport } from './routes/api/cotizacion'
import { Route as BlogImpresionBajoDemandaAutoresArgentinaRouteImport } from './routes/blog.impresion-bajo-demanda-autores-argentina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UniteRoute = UniteRouteImport.update({
  id: '/unite',
  path: '/unite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApplyRoute = ApiApplyRouteImport.update({
  id: '/api/apply',
  path: '/api/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactoRoute = ApiContactoRouteImport.update({
  id: '/api/contacto',
  path: '/api/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCotizacionRoute = ApiCotizacionRouteImport.update({
  id: '/api/cotizacion',
  path: '/api/cotizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogImpresionBajoDemandaAutoresArgentinaRoute =
  BlogImpresionBajoDemandaAutoresArgentinaRouteImport.update({
    id: '/blog/impresion-bajo-demanda-autores-argentina',
    path: '/blog/impresion-bajo-demanda-autores-argentina',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
  '/api/cotizacion': typeof ApiCotizacionRoute
  '/blog/impresion-bajo-demanda-autores-argentina': typeof BlogImpresionBajoDemandaAutoresArgentinaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
  '/api/cotizacion': typeof ApiCotizacionRoute
  '/blog/impresion-bajo-demanda-autores-argentina': typeof BlogImpresionBajoDemandaAutoresArgentinaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unite': typeof UniteRoute
  '/api/apply': typeof ApiApplyRoute
  '/api/contacto': typeof ApiContactoRoute
  '/api/cotizacion': typeof ApiCotizacionRoute
  '/blog/impresion-bajo-demanda-autores-argentina': typeof BlogImpresionBajoDemandaAutoresArgentinaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/unite'
    | '/api/apply'
    | '/api/contacto'
    | '/api/cotizacion'
    | '/blog/impresion-bajo-demanda-autores-argentina'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/unite'
    | '/api/apply'
    | '/api/contacto'
    | '/api/cotizacion'
    | '/blog/impresion-bajo-demanda-autores-argentina'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/unite'
    | '/api/apply'
    | '/api/contacto'
    | '/api/cotizacion'
    | '/blog/impresion-bajo-demanda-autores-argentina'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UniteRoute: typeof UniteRoute
  ApiApplyRoute: typeof ApiApplyRoute
  ApiContactoRoute: typeof ApiContactoRoute
  ApiCotizacionRoute: typeof ApiCotizacionRoute
  BlogImpresionBajoDemandaAutoresArgentinaRoute: typeof BlogImpresionBajoDemandaAutoresArgentinaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unite': {
      id: '/unite'
      path: '/unite'
      fullPath: '/unite'
      preLoaderRoute: typeof UniteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apply': {
      id: '/api/apply'
      path: '/api/apply'
      fullPath: '/api/apply'
      preLoaderRoute: typeof ApiApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacto': {
      id: '/api/contacto'
      path: '/api/contacto'
      fullPath: '/api/contacto'
      preLoaderRoute: typeof ApiContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cotizacion': {
      id: '/api/cotizacion'
      path: '/api/cotizacion'
      fullPath: '/api/cotizacion'
      preLoaderRoute: typeof ApiCotizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/impresion-bajo-demanda-autores-argentina': {
      id: '/blog/impresion-bajo-demanda-autores-argentina'
      path: '/blog/impresion-bajo-demanda-autores-argentina'
      fullPath: '/blog/impresion-bajo-demanda-autores-argentina'
      preLoaderRoute: typeof BlogImpresionBajoDemandaAutoresArgentinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UniteRoute: UniteRoute,
  ApiApplyRoute: ApiApplyRoute,
  ApiContactoRoute: ApiContactoRoute,
  ApiCotizacionRoute: ApiCotizacionRoute,
  BlogImpresionBajoDemandaAutoresArgentinaRoute:
    BlogImpresionBajoDemandaAutoresArgentinaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
